server:
  port: 7100

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/line
    username: root
    password: root1983
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update